### ISSUE TITLE
Festivals Dropdown not currently working

### ISSUE THREAD

**Issue by UsagiPyon** [AsgardXIV/Brio#7]
The Festivals dropdown menu is currently unavailable when in the overworld. It does appear, however, when inside an instance. 
A couple of other friends have had the same issue. 
The Brio settings window also seems to be toggled by the festival tab.

The Dalamud Console produces this error.

ERR Exception during raise of "Void UiBuilder_Draw()"
System.InvalidOperationException: Sequence contains no matching element
   at System.Linq.ThrowHelper.ThrowNoMatchException()
   at Brio.Game.World.FestivalService.get_ActiveFestivals()
   at Brio.UI.Components.World.FestivalControls.Draw()
   at Brio.UI.Windows.MainWindow.Draw()
   at Dalamud.Interface.Windowing.Window.DrawInternal(DalamudConfiguration configuration) in C:\goatsoft\companysecrets\dalamud\Interface\Windowing\Window.cs:line 317
   at Dalamud.Interface.Windowing.WindowSystem.Draw() in C:\goatsoft\companysecrets\dalamud\Interface\Windowing\WindowSystem.cs:line 152
   at Dalamud.Utility.EventHandlerExtensions.HandleInvoke(Action act) in C:\goatsoft\companysecrets\dalamud\Utility\EventHandlerExtensions.cs:line 96
{ } [ Send ]

In Ul'dah
![image](https://github.com/AsgardXIV/Brio/assets/143541558/532abfd7-bd6e-49a7-8fe3-a0b6455786df)

Error Message
![image](https://github.com/AsgardXIV/Brio/assets/143541558/2439080a-1866-4fd5-bb85-8c93b7d8b53c)

Inside Holminster Switch
![image](https://github.com/AsgardXIV/Brio/assets/143541558/4e93ab86-e866-47da-aedc-398f4e1e261f)

I hope this helps. Thank you so much for everything you do.

**Comment by AsgardXIV** [comment]
Fixed in v0.1.8.8: https://github.com/AsgardXIV/Brio/releases/tag/v0.1.8.8
